[project]
name = "ddgs-server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "ddgs>=9.8.0",
    "fastapi[standard]>=0.121.0",
    "fastmcp>=2.14.1",
    "httpx>=0.28.1",
    "slowapi>=0.1.9",
]

[dependency-groups]
dev = ["locust>=2.42.2"]
